### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by Albadylic** [oliverjam/tdd-array-methods#1]
I think this workshop is brilliant and really clear. My only concern is that it doesn't explicitly say how to run the tests  - should this just be done by running index.test.js in the console?

Student should probably know how to do this by Day 2 but I think it'd be good if this workshop could be taken in isolation in case we need to move it later.

**Comment by oliverjam** [comment]
Good point, I'll clarify in the readme. The `index.test.js` file is included in the HTML page I tell them to open in their browser. They'll need to open the console to see test results logged

**Comment by oliverjam** [comment]
Just realised the HTML file has `<h1>Open the console</h1>` 😆 

I'll add a note anyway to be clear
