### ISSUE TITLE
typo in the every() section of the READme

### ISSUE THREAD

**Issue by VatsKan** [oliverjam/tdd-array-methods#2]
"If the function returns true for every element then **_false_** is returned."

should read:
"If the function returns true for every element then **_true_** is returned."

**Comment by oliverjam** [comment]
Thanks for the reminder! I actually pushed a fix for this just before you opened it 😅 

Here's the commit for reference: https://github.com/oliverjam/tdd-array-methods/commit/5419633f118622a1a0d2e687290cae654f598328
